ExpiredPopsicle/SnekStudio

- Core/Main.gd
This fixes loading mods both when running from the project and also from a build.
On Linux, if Godot is installed using a package manager, the original code believes that the Mods folder is located at `/usr/bin/Mods`. This doesn't seem intended, as the project comes with a Mod folder included and exporting the project also creates the Mod folder where the built executable is located.
I would normally just change the filepath to load the Mods folder relative to wherever the project is located [by using `res://`](https://docs.godotengine.org/en/4.3/tutorials/io/data_paths.html#accessing-files-in-the-project-folder-res), but I think it would be nice to have a proper path in the logs. So, we also need to use `globalize_path` to get an absolute path formatted the way a user might expect it for …
> Don't try to load mod zips when in-editor

- Core/UI/ModsWindow.tscn
This fixes the issue of the scroll wheel event from propagating through sub-windows to the main scene when the mouse is hovering over the window. Note that this will cause all wheel input to not travel through to the scene when hovering over any ModWindow object.
Main scene has the unwanted effect of zooming in and out whenever wheel events aren't handled by any particular control in the tree of any ModWindow.
> ModWindow: Prevent mouse wheel input from propagating to parent

- Mods/MediaPipe/_tracker/Project/requirements.txt
- addons/KiriPythonRPCWrapper/KiriPythonBuildWrangler.gd
- addons/KiriPythonRPCWrapper/UpdateUI/PythonBuildUpdateUI.gd
- addons/KiriPythonRPCWrapper/UpdateUI/PythonBuildUpdateUI.tscn
- addons/KiriPythonRPCWrapper/platform_status.json
Add support for Linux-arm64 (aarch64). Along the way, refactor things so the architecture is included in the OS name.
This still needs some care on macOS to figure out if we should have x86_64/aarch64 separately or together using universal binaries for everything.
> Linux-arm64 support

- Mods/MediaPipe/_tracker/Project/new_tracker.py
This can happen if e.g. there are zero USB cameras connected (but there may be a non-USB camera).
> Fix exception if /dev/v4l/by-id does not exist

- Mods/HeadPats/Resources/Sprites/frame0000.png.import
- Mods/HeadPats/Resources/Sprites/frame0001.png.import
- Mods/HeadPats/Resources/Sprites/frame0002.png.import
- Mods/HeadPats/Resources/Sprites/frame0003.png.import
- Mods/HeadPats/Resources/Sprites/frame0004.png.import
- Mods/HeadPats/Resources/Sprites/frame0005.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Receiver top_Bake1_PBR_Diffuse.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Receiver top_Bake1_PBR_Metalness-Receiver top_Bake1_PBR_Roughness.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Receiver top_Bake1_PBR_Normal.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Stock_Bake1_PBR_Diffuse.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Stock_Bake1_PBR_Metalness-Stock_Bake1_PBR_Roughness.png.import
- Mods/ThrownObjects/Objects/Bastard/bastard42_baking3_Stock_Bake1_PBR_Normal.png.import
- Mods/ThrownObjects/Objects/Bit/ThrownObject_Bit_Model_ThrownObject_Bit_Texture.png.import
- Mods/ThrownObjects/Objects/Bit/ThrownObject_Bit_Splat.png.import
- Mods/ThrownObjects/Objects/GPU/GPU5_Plane-Plane.png.import
- Mods/ThrownObjects/Objects/GPU/GPU5_Plane.png.import
- Mods/ThrownObjects/Objects/GPU/GPU5_Plane_1.png.import
- icon.svg.import
- project.godot
It seems Godot by default imports textures in the format optimal for the host platform, then gets very confused if it decides it needs textures in another format for some reason (such as project export settings), and re-imports forever.
Force texture import in both main formats (ASTC, S3TC). For cross-platform collaboration, this should make sure there's no weirdness and the .import files are also universal. It's a bit slower, but pretty trivial for a projec this size.
> Import textures in S3TC and ASTC

- .github/workflows/check_update.yml
- .github/workflows/nightly.yml
Besides running nightly, there are some extra features in this workflow
* Runs builds only if there were changes in the main branch or if the latest build was unsuccessful
* Changes the project name to SnakeStudioNightly and uses git to calculate the version
* Workflows can get triggered manually through the github interface
Hope this is useful :)
> Add nightly build workflow

- .github/workflows/nightly.yml
Just noticed that I forgot a commit in my previous PR
Without this, the whole workflow fails if there is no nightly release created ... :sweat_smile:
This patch just ignores the error and makes it so that the nigthly release gets created if it doesn't exist.
> Don't fail on new project

- Mods/MediaPipe/MediaPipeController.gd
Record then average the blendshape values and then subtracting it from mediapipe output.
I have a "resting bitch face" and so my lips always seems puckered.
this will skip any eye blendshapes.
> Add face blendshape calibration

- Core/UI/UI_Root.tscn
- Mods/Base/Mod_Base.gd
This is part 1 of 2 of getting custom HDRI reflections/lighting.
This adds a button for a filedialog popup, and returns the file path back to the setting. It allows for a user friendly way to obtain a file path. 
The reason why I splitted the PRs is because this might be useful even outside of the HDRI image assignment thingy.
> Add filedialog option to lineEdit in mods

- Core/UI/BasicSliderWithNumber.tscn
I found myself unintentionally modifying settings when using the mouse wheel to scroll through a properties view (particularly the MediaPipeController mod). Prevents tracked settings properties from being modified via mouse wheel. The only case this seems to happen is the HSlider in BasicSliderWithNumber.
Fixes #65
> Prevent mouse wheel from modifying properties

- Mods/MediaPipe/MediaPipeController.gd
47a8f7007cfc modified hand position/rotation smoothing defaults from 4/2 to 1/1, making hands jittery by default. This changes the defaults back to what they once were, which should improve user experience for new users.
Fixes #68
> Fix hand smoothing defaults

- Core/UI/BasicSliderWithNumber.gd
- Core/UI/VectorSettingWidget.gd
- Mods/Base/Mod_Base.gd
Adds a button that resets tracked settings properties to their default values.
Let me know if you feel that I should use an icon, currently it just uses the unicode icon for "undo", which at least *looks* identical to the one godot uses. I also made the button flat because it looks less bulky that way. Not entirely sure how I feel about it though. If you feel like it needs adjustment let me know and I'll change it up.
I found myself sometimes unintentionally modifying settings (by accidentally clicking on them or otherwise), and I realized that I did not know what the default value for that setting was after I unintentionally modified it. Felt this was a pretty important thing to have some sort of solution for.
- Quality of Life Feature
> Add reset-to-default button to each tracked setting

- Core/UI/ModsWindow.tscn
When the mods window was resized, the mods list would also expand with it, reducing space for properties of mods unnecessarily.
This change prevents the mods listbox from expanding in order to maximize space for mod properties.
> Prevent mods list expanding when window resized

- Core/UI/UI_Root.tscn
Uses native open/save dialogs to ensure that file browsing doesn't get captured by the streaming software.
I can change this to use the godot save interface but popped out into an actual native window. Depends upon #87 to prevent the Window class from being embedded if we want to do that though.
Motivation and context behind this is that file systems are not a safe thing to be captured and streamed by streaming software and should not be embedded.
> Use native open/save file dialogs

- Core/Main.gd
- Core/Main.tscn
- Core/UI/BasicSubWindow.gd
- Core/UI/BasicSubWindow.tscn
- Core/UI/ModAddWindow.gd
- Core/UI/ModsWindow.gd
- Core/UI/ModsWindow.tscn
- Core/UI/SettingsWindow_ChannelEvents.gd
- Core/UI/SettingsWindow_Colliders.gd
- Core/UI/SettingsWindow_General.gd
- Core/UI/SettingsWindow_Scene.gd
- Core/UI/SettingsWindow_Sound.gd
- Core/UI/SettingsWindow_Window.gd
- Core/UI/SettingsWindow_Window.tscn
- Core/UI/UI_Root.gd
- Core/UI/UI_Root.tscn
- Mods/Base/Mod_Base.gd
- project.godot
Adds the ability to pop out certain subwindows as native windows.
Changes included:
- The ability to pop out certain subwindows (mods/settings windows)
- An API for serializing dimensions/popout/state
- Fixes the mods log listbox expanding and taking up space unnecessarily
- Saves the current dimensions of subwindows, both when popped out and when embedded separately
- Saves/loads the offsets of the mod list and mod log vertical/horizontal splitters in the mods window
> [!NOTE]
> When embedded, the popout button is displayed to the left of the `[x]` button as a `[p]`. Because the buttons are so small, and because text is used, anything else I try feels weirdly inconsistent with the `[x]` button. I am slightly concerned that most users may not see this or realize they can pop out the …
> Add ability to pop out key subwindows

- addons/KiriPythonRPCWrapper/KiriPythonBuildWrangler.gd
related: #92 
e.g., in case the user downloaded the arm build instead
of x86_64, this tells them what the expected path was
and what they currently have
Dunno if this is too verbose of an alert of it should just be printed, first time ever using godot so
am quite new to this
> KiriPythonBuildWrangler: nicer warning if mismatched archive

- Mods/Twitch/TwitchIntegration.gd
it was adding it to the tree, which starts oauth flow, before providing the oauth client id.
> fix twitch integration initialization

- Core/Main.gd
- Core/ModelController.gd
- Core/UI/BasicSubWindow.gd
- Core/UI/ModAddWindow.gd
- Core/UI/SettingsWindow_General.gd
- Mods/Base/Mod_Base.gd
- Mods/MediaPipe/MediaPipeController.gd
Fixes approximately 24 runtime warnings.
Just noticed various warnings, some of which I introduced, some of which were already there. I figured I'd get rid of them.
> [!NOTE]
>
> This leaves one warning behind as of this commit, but it's mostly because there's a fair amount of code after a return statement and I'm unsure if it's intended to leave that code
- Code cleanup
> Fix various runtime warnings

- Core/UI/UI_Root.tscn
The default size of the "Add Mod" window was a bit small. This increases the default size to make the list and description text a bit less squimshed.
The squimshed window for mod selection/description was a bit awkward when adding a mod.
- Tweak (non-breaking change to improve existing functionality)
> Make "Add Mod" window bigger

- Core/UI/BasicSubWindow.gd
When popping a window back in after it's been popped out, the reparent() call will cause the window to reposition relative to its parent, which causes the embedded version of a window to move down a bit, so if you don't want the position of a window to be modified, you have to set the window position/size *after* the reparent() call. Learned this after debugging into the engine code itself.
- Tweak (non-breaking change to improve existing functionality)
> Fix window moving down when popping in

- Core/UI/BasicSubWindow.gd
- Core/UI/ModAddWindow.gd
- Core/UI/ModsWindow.gd
- Core/UI/UI_Root.tscn
Makes the Add Mod window actually usable while the Mods window is popped out in its own window.
There were a number of issues with the Add Mod window when the Mods window was popped out:
- It would crash due to reliance on relative path node lookup (the Add Mod window now uses a unique scene identifier)
- The Add Mod window could go behind the main window or behind the Mod window (it's now modal when popped out)
- The Add Mod window should probably not able to individually be popped back in (removed the Popin option for the Add Mod window when the Mod window is popped out)
- Bug fix (non-breaking change which fixes an issue)
- Tweak (non-breaking change to improve existing functionality)
> Make Add Mod window usable while Mods window popped out

- Core/UI/UI_Root.gd
- Core/UI/UI_Root.tscn
Currently, input events are completely captured by the root / main UI when it is visible, preventing you from using `_input_event` and similar with 3D nodes. This PR changes this behavior such that events are allowed to pass through, unless they are handled by the UI, including making sure that the default camera controls call `set_input_as_handled()`.
> Input events propagate with UI Root open

- Core/Main.gd
Fixes an issue in `Main.save_settings()` where, if the settings directory doesn't already exist, settings don't actually persist when closing the application normally. Especially noticeable when using `SNEKSTUDIO_CONFIG_PATH`. Such a check doesn't appear to be necessary for `SNEKSTUDIO_CACHE_PATH` – it is created just fine.
> Create settings directory if it doesn't exist

- Mods/MediaPipe/MediaPipeController.gd
Related issue: #116
Slight issue with the tracking being disabled on main branch due to some return statements in the process function of MediaPipeController.
These were introduced in this commit #https://github.com/ExpiredPopsicle/SnekStudio/commit/5033b8c181f720f17f5247f6bf669110ee935520
Reverting these changes makes model tracking work again.
> Fix: Tracking disabled due to IK processing skipped

- Mods/MediaPipe/MediaPipeController.gd
The flag was previously doing nothing since the `_update_hand_tracker` method used `parsed_data[hand_score_str]` instead of `hand_score` at a couple of places. The flag now works as intended.
(And thanks for this awesome software <3, it's just amazing and way better to use under linux than the painfull VSeeFace setup I tried to get to work before.)
> Fixes hand_tracking_enabed not having any effect

- Mods/MediaPipe/MediaPipeController.gd
This just adds settings for head smoothing in the MediaPipeController mod, that were previously hardcoded values
> Expose head position/rotating scaling options in MediaPipeController
